### ISSUE TITLE
Bring readme.md inline with the code.

### ISSUE THREAD

**Issue by janvda** [travisghansen/node-red-slack#3]
The readme.md is still documenting the old nodes (slack version 1.2.0).
So the readme.md must be updated to document the new slack nodes.

**Comment by travisghansen** [comment]
This is done.  I'll leave the issue open for now until you have a chance to provide feedback so it can be updated.  Thanks!

**Comment by janvda** [comment]
Thanks a lot.  You have written quite some extensive set of documentation !

**Comment by travisghansen** [comment]
Thanks!  I've just updated it a bit more to be more clear and have better linking to both internal and external resources.  Once the `README.md` is looking good I'll move over to the in-Node-RED documentation (ie: from the palette) borrowing as much as possible from the `README.md` file.

**Comment by janvda** [comment]
I think that following paragraph regarding `dressed response` might require an extra look:

> All responses/events are traversed before output to automatically do lookups on your behalf to add additional info directly into the msg.payload (examples provided below). All of the lookups are done dynamically/generically so regardless of what API response you get if the node finds an attribute that appears to be a supported object (user/channel/team/bot) in some shape or form, a corresponding <attribute>Object attribute with the lookup value will be added.

It was not immediately clear what you meant by `dressed response`.  I think you need to say something like that the msg.payload in all responses of these slack nodes is extended with additional information (examples provided below) about slack (user/channel/team/bot).

**Comment by travisghansen** [comment]
Thanks for the input!  I'll re-read this and see if I can make it more clear.

**Comment by travisghansen** [comment]
@janvda is this more clear?

## `dressed` output

The following nodes each provide
<a href="https://api.slack.com/" target="_new">Slack API</a> output:

- [`slack-rtm-in`](#slack-rtm-in)
- [`slack-rtm-out`](#slack-rtm-out)
- [`slack-web-out`](#slack-web-out)

The respective events/responses are generally left unaltered and are directly
passed through as `msg.payload`. However, before outputting the `msg` the data
is traversed to enrich the `msg.payload` (examples provided below) with
complete object data where otherwise only inernal Slack IDs are present.

All of the lookups are done dynamically/generically so regardless of what API
response you get if the node finds an attribute that appears to be a
supported object (`user`/`channel`/`team`/`bot`) in some shape or form, a
corresponding `<attribute>Object` attribute with the lookup value will be
added.

For example, if the response contains a `bot_id` attribute you would see
`bot_idObject` added, or if it found an attribute called `bot` it would add
`botObject` etc. Ultimately all the lookups com from
[`slackState`](#slackstate) (see below) so it could be done on your own but
it's added to simplify and for convenience.

An example
<a href="https://api.slack.com/events/user_typing" target="_new">`user_typing`</a>
event from the [`slack-rtm-in`](#slack-rtm-in) node:

```
{
  "type": "user_typing",
  "channel": "...",
  "user": "..."
}
```

is `dressed` to be sent as:

```
{
  "type": "user_typing",
  "channel": "...",
  "user": "...",
  "channelObject": {
    "id": "...",
    "name": "...",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1434735155,
    ...
  },
  "userObject": {
    "id": "...",
    "name": "...",
    "real_name": "...",
    ...
  }
}
```

**Comment by janvda** [comment]
Looks much better.

Some little typos: `inernal Slack IDs` should be  `internal Slack IDs` 
and `Ultimately all the lookups com from` should be `Ultimately all the lookups come from`

In the beginning you write:
>>>The following nodes each provide
Slack API output:

The problem I have when clicking on the `Slack API` link is that I land on the general Slack API page (=  https://api.slack.com/web) and that it is not very clear to me where I can find the specifications of the actual Slack API output that is generated by those nodes.

**Comment by travisghansen** [comment]
@janvda great feedback.  I'm committed a minor update.

**Comment by janvda** [comment]
small typo in the slack-web-out Node Help:
`If you use this syntax simply set msg.payload the the message you want sent.`
should be 
`If you use this syntax simply set msg.payload to the message you want sent.`

**Comment by travisghansen** [comment]
@janvda thanks!  I'll get it corrected.

**Comment by travisghansen** [comment]
@janvda just added examples in each of the node definitions in the `README.md` as well.  With that in place and the committed lock file I think we're code complete ready for publishing to npm.

**Comment by janvda** [comment]
Excellent, i consider this issue closed - thanks a lot.
